DBZ-6262 Enable pass through configurations for internal sync topic
debezium/debezium-connector-spanner pull request #32
Opened 2023-04-03 20:46 UTC by ShuranZhang

Enable the user to configure arbitrary configurations for sync topic with prefix "connector.spanner.sync.topic.internal.*".

Context: https://debezium.zulipchat.com/#narrow/stream/302529-users/topic/High.20CPU.20consumption.20in.20Spanner.20debezium/near/344217302

For example, this pr will enable users to configure the compression type by setting ' "connector.spanner.sync.topic.internal.compression.type" : "gzip" ' in config JSON file for kafka connector.
Temporary log message used for testing(now removed):
![Screenshot 2023-04-03 at 1 39 45 PM](https://user-images.githubusercontent.com/43364656/229623556-187ba027-2d07-4f81-a6a9-78b318ee7e7f.png)

2023-04-04 09:06 UTC, jpechane requested changes
Please extend the scope of the issue to cover all topics and also all producer and consumer factories. It is not going to be a lot of code yet it will be very useful for the user.

2023-04-05 18:23 UTC, ShuranZhang commented on src/main/java/io/debezium/connector/spanner/db/dao/SchemaDao.java
> +        return resultSet.getBoolean(index);
Done.

2023-04-05 18:24 UTC, ShuranZhang commented on src/main/java/io/debezium/connector/spanner/config/BaseSpannerConnectorConfig.java
> +    public static final String CONNECTOR_SPANNER_SYNC_TOPIC_INTERNAL_PREFIX = "connector.spanner.sync.topic.internal.";
Done.

2023-04-05 18:24 UTC, ShuranZhang commented on src/main/java/io/debezium/connector/spanner/kafka/internal/KafkaInternalTopicAdminService.java
> +                Map<String, String> syncTopicInternalProps = config.getConfig().asMap().entrySet()
Done.

2023-04-05 18:57 UTC, ShuranZhang commented
> Please extend the scope of the issue to cover all topics and also all producer and consumer factories. It is not going to be a lot of code yet it will be very useful for the user.

I have added same feature for rebalancing topic. For all the producer and consumer factories, this feature is already included since all consumer and producer factories utilize [kafkaProps](https://github.com/debezium/debezium-connector-spanner/blob/d6dfb6fb761117142ba5af9e6af61f576273aec2/src/main/java/io/debezium/connector/spanner/SpannerConnectorConfig.java#L80), and all pass through configurations with prefix [KAFKA_INTERNAL_CLIENT_CONFIG_PREFIX](https://github.com/debezium/debezium-connector-spanner/blob/d6dfb6fb761117142ba5af9e6af61f576273aec2/src/main/java/io/debezium/connector/spanner/config/BaseSpannerConnectorConfig.java#L94) have been extracted to this kafkaProps. See this example usage form [ProducerFactory](https://github.com/debezium/debezium-connector-spanner/blob/main/src/main/java/io/debezium/connector/spanner/kafka/internal/ProducerFactory.java#L29).

2023-04-06 04:39 UTC, jpechane approved these changes
@ShuranZhang LGTM, thanks! Waiting for ready/test label before merging.
In the meantime could you please prepare a separate PR in the main repo with docs update?

2023-04-06 04:57 UTC, ShuranZhang commented
> @ShuranZhang LGTM, thanks! Waiting for ready/test label before merging. In the meantime could you please prepare a separate PR in the main repo with docs update?

Added the label and will work on updating the doc with in a separate pr. Thanks!

2023-04-06 05:01 UTC, merged

2023-04-06 05:01 UTC, jpechane commented
@ShuranZhang Applied, thanks!